### ISSUE TITLE
Implement API filter/search based on PMID

### ISSUE THREAD

**Issue by nkicg6** [ourresearch/openalex-guts#1]
API Search by DOI works great:
- `http://api.openalex.org/works/https://doi.org/10.1038/nature23884`
- `http://api.openalex.org/works?filter=doi:https://doi.org/10.1038/nature23884` 

return the expected work. However, pmid does not work:
- `http://api.openalex.org/works?filter=pmid:https://pubmed.ncbi.nlm.nih.gov/28905911` 
- `http://api.openalex.org/works/https://pubmed.ncbi.nlm.nih.gov/28905911` 

Any plans to implement this? 

Happy to contribute with a little guidance! Let me know if this belongs in https://github.com/ourresearch/openalex-elastic-api instead.

**Comment by richard-orr** [comment]
Yes, we should be able make both examples work. Right now each fails for a different reason.

https://api.openalex.org/works?filter=pmid:https://pubmed.ncbi.nlm.nih.gov/28905911 doesn't work because pmid isn't one of the [filterable attributes on Works](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#works-attribute-filters). Granted, _doi_ isn't listed there either and it works. There's no reason we can't add pmid as a filter, and certainly we need to add _doi_ to the documentation.

https://api.openalex.org/works/https://pubmed.ncbi.nlm.nih.gov/28905911 doesn't work because, while _pmid_ is one of the [supported ids](https://docs.openalex.org/api/get-single-entities#supported-ids) for [Works](https://docs.openalex.org/about-the-data/work#ids), we're giving it as a URL and expecting to receive it [as an integer.](https://en.wikipedia.org/wiki/PubMed#PubMed_identifier). Another disconnect between the docs and the API, we'll get that fixed.

In the meantime: PMID lookups work if you use the same form as other integer IDs: [https://api.openalex.org/works/pmid:28905911](https://api.openalex.org/works/pmid:28905911). We'll keep that working regardless of how we reconcile the docs and API behavior.

**Comment by richard-orr** [comment]
Forgot to add: we're going to consolidate OpenAlex bug reports to a single email address in the near future, but for now issues on any of the associated repos are appreciated.
